package uk.gov.moj.cpp.sjp.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.stagingdvla.handler.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - stagingdvla.command.driver-notification"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingdvla.command.driver-notification");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCommandDriverNotify()));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - stagingdvla.command.generate-driver-record-search-audit-report"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingdvla.command.generate-driver-record-search-audit-report");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCommandDriverSearchAudit()));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - stagingdvla.command.delete-driver-record-search-audit-report"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingdvla.command.delete-driver-record-search-audit-report");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getCommandDriverSearchAudit()));
  then
    $outcome.setSuccess(true);
end
