#%RAML 0.8
title: stagingdvla Query
version: v0.1
protocols: [ HTTP, HTTPS ]

baseUri: http://localhost:8080/stagingdvla-query-api/query/api/rest/stagingdvla

/driver/{driverNumber}:
  description: return a driver
  uriParameters:
      driverNumber:
        description: driverNumber
        type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.stagingdvla.query.drivernumber+json
          name: stagingdvla.query.drivernumber
      ...
    queryParameters:
      caseId:
        description: Case ID
        type: string
        example: 41C12017614
        required: false
      reasonType:
        description: Driver Audit Reason Type
        type: string
        example: CE CASE ENQUIRY or FPE FIXED PENALTY ENQUIRY
        required: true
      reference:
        description: Case Urn or Ticket Number
        type: string
        example: 87GD9945217
        required: true

    responses:
      200:
        body:
          application/vnd.stagingdvla.query.drivernumber+json:
            schema: !include json/schema/stagingdvla.query.drivernumber.json
            example: !include json/stagingdvla.query.drivernumber.json

/drivers:
  description: return a driver list
  get:
    description: |
      ...
      (mapping):
        responseType: application/vnd.stagingdvla.query.driverdetails+json
        name: stagingdvla.query.driverdetails
      ...
    queryParameters:
      lastName:
        description: Driver's last name
        type: string
        example: SMITH
        required: false
      firstNames:
        description: Driver's first names
        type: string
        example: JOHN
        required: false
      dateOfBirth:
        description: Driver's date of birth in format 'YYYY-MM-DD'
        type: string
        example: 2000-01-01
        required: false
      postcode:
        description: Driver's postcode
        type: string
        example: CR0 2AB
        required: false
      gender:
        description: Driver's gender
        type: string
        example: Male
        required: false
      caseId:
        description: Case Id
        type: string
        example: 41C12017614
        required: false
      exactFirstNamesMatch:
        description: Indicates whether an exact match search is required for firstNames
        type: string
        example: true
        required: false
      reasonType:
        description: Driver Audit Reason Type
        type: string
        example: CE CASE ENQUIRY or FPE FIXED PENALTY ENQUIRY
        required: true
      reference:
        description: Case Urn or Ticket Number
        type: string
        example: 87GD9945217
        required: true
    responses:
      200:
        body:
          application/vnd.stagingdvla.query.driverdetails+json:
            schema: !include json/schema/stagingdvla.query.driverdetails.json
            example: !include json/stagingdvla.query.driverdetails.json

/driving-conviction-retry/{maxCount}:
  description: return a list of driving conviction retry records
  uriParameters:
    maxCount:
      description: max record count in response
      type: integer
  get:
    description: |
      ...
      (mapping):
        responseType: application/vnd.stagingdvla.query.driving-conviction-retry+json
        name: stagingdvla.query.driving-conviction-retry
      ...
    responses:
      200:
        body:
          application/vnd.stagingdvla.query.driving-conviction-retry+json:
            schema: !include json/schema/stagingdvla.query.driving-conviction-retry.json
            example: !include json/stagingdvla.query.driving-conviction-retry.json


/driver/{driverNumber}/image:
  description: return a driver image i.e. photograph and signature
  uriParameters:
      driverNumber:
        description: driverNumber
        type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.stagingdvla.query.driverimage+json
          name: stagingdvla.query.driverimage
      ...
    queryParameters:
      requiredImage:
        description: Photograph or signature
        type: string
        example: Photograph | signature
        required: false
    responses:
      200:
        body:
          application/vnd.stagingdvla.query.driverimage+json:
            schema: !include json/schema/stagingdvla.query.driverimage.json
            example: !include json/stagingdvla.query.driverimage.json


/driver-audit-records:
  description: return  driver audit records
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.stagingdvla.query.driver-audit-records+json
          name: stagingdvla.query.driver-audit-records
      ...
    queryParameters:
      email:
        description: email address for search
        type: string
        example: perter21@uk.com
        required: false
      driverNumber:
        description: driver number for search
        type: string
        example: DRIVER1002101212122
        required: false
      startDate:
        description: start date for search
        type: string
        example: 2000-01-01
        required: true
      endDate:
        description: end date for search
        type: string
        example: 2000-01-01
        required: true

    responses:
      200:
        body:
          application/vnd.stagingdvla.query.driver-audit-records+json:
            schema: !include json/schema/stagingdvla.query.driver-audit-records.json
            example: !include json/stagingdvla.query.driver-audit-records.json


/driver-search-audit-reports:
  description: get driver audit reports for logged in user
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.stagingdvla.query.driver-search-audit-reports+json
          name: stagingdvla.query.driver-search-audit-reports
      ...
    responses:
      200:
        body:
          application/vnd.stagingdvla.query.driver-search-audit-reports+json:
            schema: !include json/schema/stagingdvla.query.driver-search-audit-reports.json
            example: !include json/stagingdvla.query.driver-search-audit-reports.json


/driver-audit-report/{reportId}/material/{materialId}:
  uriParameters:
    reportId:
      description: report id
      type: string
      example: c44fa9bb-dc36-4375-83a9-ff1bc4cd4374
    materialId:
      description: material id
      type: string
      example: b44fa9bb-dc36-4375-83a9-ff1bc4cd4374
  get:
    description: |
      Query the material created with driver search audit report
      ...
      (mapping):
          responseType: application/vnd.stagingdvla.query.driver-search-audit-report-content+json
          name: stagingdvla.query.driver-search-audit-report-content
      ...
    responses:
      200:
        description: OK
        body:
          application/vnd.stagingdvla.query.driver-search-audit-report-content+json:
