#%RAML 0.8
title: staging dvla Command handler
version: 1.0
baseUri:  message://command/handler/message/stagingdvla


/stagingdvla.handler.command:
  post:
      body:
        application/vnd.stagingdvla.command.handler.driver-notification+json:
          example:  !include json/stagingdvla.command.handler.driver-notification.json
          schema: !include json/schema/stagingdvla.command.handler.driver-notification.json
        application/vnd.stagingdvla.command.record-nows-material-request+json:
          example:  !include json/stagingdvla.command.record-nows-material-request.json
          schema: !include json/schema/stagingdvla.command.record-nows-material-request.json
        application/vnd.stagingdvla.command.send-email-notification+json:
          example:  !include json/stagingdvla.command.send-email-notification.json
          schema: !include json/schema/stagingdvla.command.send-email-notification.json
        application/vnd.stagingdvla.command.handler.schedule-next-retry-for-driver-notified+json:
          example:  !include json/stagingdvla.command.handler.schedule-next-retry-for-driver-notified.json
          schema: !include json/schema/stagingdvla.command.handler.schedule-next-retry-for-driver-notified.json
        application/vnd.stagingdvla.command.handler.trigger-next-retry-for-driver-notified+json:
          example: !include json/stagingdvla.command.handler.trigger-next-retry-for-driver-notified.json
          schema: !include json/schema/stagingdvla.command.handler.trigger-next-retry-for-driver-notified.json
        application/vnd.stagingdvla.command.handler.audit-driver-record+json:
          example: !include json/stagingdvla.command.handler.audit-driver-record.json
          schema: !include json/schema/stagingdvla.command.handler.audit-driver-record.json
        application/vnd.stagingdvla.command.handler.generate-driver-record-search-audit-report+json:
          example: !include json/stagingdvla.command.handler.generate-driver-record-search-audit-report.json
          schema: !include json/schema/stagingdvla.command.handler.generate-driver-record-search-audit-report.json
        application/vnd.stagingdvla.command.handler.driver-record-search-audit-report-created+json:
          example: !include json/stagingdvla.command.handler.driver-record-search-audit-report-created.json
          schema: !include json/schema/stagingdvla.command.handler.driver-record-search-audit-report-created.json
        application/vnd.stagingdvla.command.handler.driver-record-search-audit-report-stored+json:
          example: !include json/stagingdvla.command.handler.driver-record-search-audit-report-stored.json
          schema: !include json/schema/stagingdvla.command.handler.driver-record-search-audit-report-stored.json
        application/vnd.stagingdvla.command.handler.delete-driver-record-search-audit-report+json:
          example: !include json/stagingdvla.command.handler.delete-driver-record-search-audit-report.json
          schema: !include json/schema/stagingdvla.command.handler.delete-driver-record-search-audit-report.json

